apiVersion: apps/v1
kind: Deployment
metadata:
  name: coralogix-operator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coralogix-operator-app
  template:
    metadata:
      labels:
        app: coralogix-operator-app
    spec:
      containers:
      - name: coralogix-operator-container
        image: 206347171/coralogix_operator
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
