apiVersion: v1
kind: Service
metadata:
  name: coralogix-operator-service
  labels:
    app: coralogix-operator-app
spec:
  ports:
    - name: web
      port: 2112
      protocol: TCP
  selector:
    app: coralogix-operator-app