apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: log-reader
rules:
  - apiGroups: ["stable.coralogix.com"] # "" indicates the core API group
    resources: ["logs"]
    verbs: ["get", "watch", "list"]
  